// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://polrgtkcwsxjsbnnqoox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvbHJndGtjd3N4anNibm5xb294Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MTk4NTIsImV4cCI6MjA3NDQ5NTg1Mn0.8Uf_2WIg2zl0TEF2TjTG0I8u3vk4a41tkamgkaWuE-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});